### ISSUE TITLE
留言: 面试经验

### ISSUE THREAD

**Issue by KelvinZyf** [tancolo/MOOC#2]
现在才换了工作，还是做Android，16年毕业，刚毕业的时候面试问的问题基本是比较基础的内容，算法，计算机系统什么，现在面试内容可谓是五花八门，既有最新的技术也有基础的技术，总之怎么难怎么来，不过不管面试遇到什么面试完一定要总结。现在面试大部分会问 OK3、RX系列、Handler消息机制还是会问、算法（一般大公司会问这个）、音视频、还有就是会问你实际开发中遇到的问题即解决办法（也是为了辨别是否是真是工作吉言吧）。面试挺难，但是要相信明天会更好。

**Comment by tancolo** [comment]
活动结束 关闭
