### ISSUE TITLE
哈哈，过来学习了

### ISSUE THREAD

**Issue by NightsSky** [tancolo/MOOC#4]
##  项目结果清晰明了，有点像google官方的MVP例子，但看起来更容易理解，很适合MVP入门。

但是希望出一点更深入的mvp封装的例子， 比如：

- 虽然项目中使用了 Contract 来管理 view 和 presenter但是项目结果大之后还是会有很多重复的接口代码，怎样在MVP中提高代码复用性。
- 现在不都流行 rxjava + retrofit + dagger2 +mvp么 ，来搞一个呗，特别是dagger2的运用，我用着一直不顺手。

**Comment by tancolo** [comment]
活动结束 关闭
