### ISSUE TITLE
檀工！檀工！檀 神！大  神

### ISSUE THREAD

**Issue by GuZhC** [tancolo/MOOC#5]
自己自学的安卓，原来开始写一些小程序，写完之后发现自己写的特别乱，真的是不想再动这个代码了，越到后面这种感觉越强烈。
主要原因还是自己的方式不对，后来看了 檀工的这个教程，开始用MVP写发现清晰了很多。排斥感少了非常多。从一个菜鸟到高手，需要走很多的坑，，遇到一个好课程，一个好老师真的是少走了很多弯路，MVp,Rxjava,封装，这些都应该是必备的技能，感谢檀工。

**Comment by tancolo** [comment]
活动结束 关闭
