### ISSUE TITLE
tabLayout.addTab(tabLayout.newTab()); 为什么写两遍呢

### ISSUE THREAD

**Issue by zuumau** [tancolo/MOOC#8]
MovieDetailActivity  
第 56 行  
            tabLayout.addTab(tabLayout.newTab());
            tabLayout.addTab(tabLayout.newTab());
这两行代码相同，为什么要写两遍呢

**Comment by tancolo** [comment]
MovieDetailActivity 里面应该有2个Tab， 需要有2个.
你可以注释掉试试， 看看效果。
还有，从你描述上看，你使用的是master分支代码，当然也没有啥大问题，只是 mvp-dev-more分支比master分支 提交的更多些。
